format_version: 3
pipelines:
  GitHub:
    group: My-Pipelines
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: git@github.com:reachsaiv/sfdxCI.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          testTask:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - Hello World
                command: echo
                run_if: passed
